services:
  leandrosantosmega:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leandrosantosmega
    restart: always
    expose:
      - "8081:80"
    networks:
      - laravel-network

networks:
  laravel-network:
    external: true
