services:
  meu-php-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leandrosantosmega
    restart: always
    expose:
      - "8081"
    networks:
      - laravel-network
